apiVersion: v1
kind: Service
metadata:
  name: cluster-example
  labels:
    run: cluster-example
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    run: cluster-example
---
apiVersion: v1
kind: Service
metadata:
  name: cluster-example-discovery
  labels:
    run: cluster-example
spec:
  clusterIP: None
  ports:
  - port: 80
    protocol: TCP
  selector:
    run: cluster-example
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cluster-example
spec:
  selector:
    matchLabels:
      run: cluster-example
  replicas: {{.Values.nodeCount}}
  template:
    metadata:
      labels:
        run: cluster-example
    spec:
      containers:
      - name: cluster-example
        image: cluster1
        imagePullPolicy: Never
        env:
        - name: CLUSTER_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: CLUSTER_NODE_COUNT
          value: "{{.Values.nodeCount}}"
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /healthz
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 10
          failureThreshold: 12
          